### ISSUE TITLE
As a user I want to be able to see a crosshair overlay on the image capture screen, so I can position my item correctly

### ISSUE THREAD

**Issue by paulhands** [bin-nuance-bat/project#119]
AC:

- Crosshair matching UX is displayed on the image capture webcam display
- Animation of crosshair - linked to binary success initially
- Add "Snack recognised!" to the header when the animation starts

**Comment by KyleADay** [comment]
Animation looks good, however it says 'Snack recognised!' even if the snack is not recognised, which leads to confusion as it then redirects to the 'Sorry I can't recognise that snack' `/editsnack` page. See screenshots: 

<img src="https://user-images.githubusercontent.com/41333766/43643813-636f63ec-9724-11e8-9a24-a94707e6444e.png" width="192" height="256" /> <img src="https://user-images.githubusercontent.com/41333766/43643822-67ebc578-9724-11e8-87aa-681ab66566f0.png" width="192" height="256" /> <img src ="https://user-images.githubusercontent.com/41333766/43644502-d5a52666-9726-11e8-85cf-a24839e1ad42.png" width="192" height="256" />
