### ISSUE TITLE
Release Snackchat

### ISSUE THREAD

**Issue by paulhands** [bin-nuance-bat/project#126]
AC:

- SnackChat is released to be used by the office at the honesty store kiosk

**Comment by Brownie956** [comment]
This only works in Chrome at the moment. It needs to ultimately work in Safari

**Comment by Brownie956** [comment]
There still exists CSS issues with the SnackChat side of things. Following discussions around the immediate progression with SnackChat, I'm moving this ticket and #60 into ToDo where we will temporarily put a pin in them.
