### ISSUE TITLE
UX: Slackname selection 

### ISSUE THREAD

**Issue by HelloUniverseNo31415** [bin-nuance-bat/project#194]
## NAME OF PAGE/COMPONENT
Username Entry /Slackname

## PART OF DESIGN NOT MATCHING
Images don't have a border

**Comment by isaac-lapworth** [comment]
Can't seem to find a UX design for the border. When #216 (adding border-radius) is merged the icons will match the current specification on Google Drive

**Comment by paulhands** [comment]
Closing this as not relevant. Miscommunication on border and border radius. Radius already done
