### ISSUE TITLE
BUG: Denying webcam access prevents the user from scanning an item until the page is refreshed

### ISSUE THREAD

**Issue by cainy393** [bin-nuance-bat/project#196]
## DESCRIPTION

**Steps to reproduce:** 
- When the app is navigated to the scan item screen for the first time since page load, they deny access to the camera

**Expected behaviour:** 
- Upon the next user attempting to scan an item, if permission is not already granted, it should be requested again.

**Observed behaviour:** 
- Permission is not requested after the initial request is denied. This renders the app unusable until the page is refreshed.

**Comment by tclarke-scottlogic** [comment]
The Home Page now reserves camera access, so this is no longer such an issue.
