### ISSUE TITLE
BUG: failed fetch requests ignored/retried indefinitely when internet access is lost

### ISSUE THREAD

**Issue by isaac-lapworth** [bin-nuance-bat/project#200]
## DESCRIPTION

**Steps to reproduce:** 
- Start the app and follow the flow to a page that makes a network request - e.g. the item recognition page
- Turn off the device's internet connection

**Expected behaviour:** 
- When the request fails the app should display a 'Please check your Internet connection' message or something of the sort

**Observed behaviour:** 
- Depending on the page, the failed requests are ignored or retried in a loop
- For example, the item recognition page shows no indication of losing connection and the webcam feed is displayed indefinitely - the user may think they are still scanning their item

**Comment by hcampbellUX** [comment]
![screen shot 2018-07-30 at 15 44 46](https://user-images.githubusercontent.com/23166345/43405542-ff6f0b50-9411-11e8-9ee7-7d68972aaedf.png)

**Comment by KyleADay** [comment]
The offline message appears as expected on all pages. However, when on the homepage and switching back online, the offline message reloads/reappears before disappearing. This only happens on the homepage.

Also, when switching between online and offline on the `\scanitem` page, the video eventually fails to load (usually after two times), and causes the screen to freeze.
