### ISSUE TITLE
Disclaimer - More Padding under the accept and continue button

### ISSUE THREAD

**Issue by siobhanobrien** [bin-nuance-bat/project#202]
## NAME OF PAGE/COMPONENT
Send Reminder & Disclaimer 
## PART OF DESIGN NOT MATCHING
We have altered the spec of the 'Send reminder' and 'Accept and continue' buttons so that they will both be aligned when clicking through screens. Please see Helen's comment below with the attached spec.

**Comment by hcampbellUX** [comment]
[Aligned buttons.pdf](https://github.com/bin-nuance-bat/project/files/2235985/Aligned.buttons.pdf)

Here is a small spec of the button heights
