### ISSUE TITLE
Quick Search Bubble - No quick scroll bubble

### ISSUE THREAD

**Issue by siobhanobrien** [bin-nuance-bat/project#203]
## NAME OF PAGE/COMPONENT
Quick Search Bubble Slack & Snack
## PART OF DESIGN NOT MATCHING
There is no blue quick search bubble indicating the letter selected when scrolling through the A-Z panel.

**Comment by isaac-lapworth** [comment]
@siobhanobrien Please could you link me the assets for the bubble? - can't see them on Google Drive

**Comment by siobhanobrien** [comment]
@isaac-lapworth https://drive.google.com/file/d/1fGF_9lA21DVIe7OiI5WyG7z3xTw4v7jq/view?usp=sharing
