### ISSUE TITLE
Reminder Sent - Remove 'Are you still there' pop up

### ISSUE THREAD

**Issue by siobhanobrien** [bin-nuance-bat/project#207]
## NAME OF PAGE/COMPONENT
Reminder Sent
## PART OF DESIGN NOT MATCHING
Instead of leaving it on the reminder sent screen until an 'are you still there' pop appears, after 10 seconds of the reminder sent screen appearing just refresh to the homepage without asking the user, as it is the end of the user journey.

**Comment by KyleADay** [comment]
After 10 seconds, the reminder sent screen refreshes to the homepage with no 'are you still there' message.
