### ISSUE TITLE
Honesty Store Logo - Remove it 

### ISSUE THREAD

**Issue by siobhanobrien** [bin-nuance-bat/project#222]
## NAME OF PAGE/COMPONENT
All Screens
## PART OF DESIGN NOT MATCHING
Remove the honesty store logo

**Comment by isaac-lapworth** [comment]
Logo is still present in UX spec - need confirmation of where to replace with back buttons to continue

**Comment by siobhanobrien** [comment]
@isaac-lapworth https://drive.google.com/file/d/16ee202YhVJ1f1-3c9zMwaO-ZTJLBvQxI/view?usp=sharing please find the spec without the HS logo linked here.

**Comment by KyleADay** [comment]
The Honesty Store logo has been removed from all pages
