### ISSUE TITLE
UX: Re-organise alphabetical selection bar on search pages

### ISSUE THREAD

**Issue by cainy393** [bin-nuance-bat/project#227]
## NAME OF PAGE/COMPONENT

Edit Snack and Slack Name pages

## PART OF DESIGN NOT MATCHING

Include all letters from A-Z in the list and place the # section at the bottom as opposed to the top.

**Comment by chrisprice** [comment]
Please keep location of numbers to match existing app

**Comment by KyleADay** [comment]
@chrisprice confirmed to keep # section on top for sorting consistency, so this issue can be closed
