### ISSUE TITLE
Setup release protocol

### ISSUE THREAD

**Issue by paulhands** [bin-nuance-bat/project#234]
AC:

- Ensure Dev is up to date with master, or cherry pick separate branches from dev for different PRs in future
- Delete dev branch
- Setup honesty-store-kiosk-QA site
- Setup private branches env-QA and env-Prod
- Setup automatic deployment to respective sites for branches
- Change master automatic deployment to point to honesty-store-kiosk-dev
...

**Comment by Brownie956** [comment]
The `env-qa` branch needs protection added to it + myself and @KyleADay to be set as 'code owners' on the branch

**Comment by Brownie956** [comment]
@eclennett Set up code owner protection on the `env-qa` branch
