### ISSUE TITLE
BUG: When in iPad landscape mode, the main page ‘Send a reminder’ button isn’t centred and there is a white background at the bottom.

### ISSUE THREAD

**Issue by KyleADay** [bin-nuance-bat/project#238]
## DESCRIPTION

**Steps to reproduce:** 
- Start the app and turn to landscape mode
- Scroll to the bottom of the main page

**Expected behaviour:** 
- The button should be centred
- The background should remain blue

**Observed behaviour:** 
- The button is to the right
- A white background appears at the bottom of the page

![238 honesty-store-kiosk firebaseapp com_ ipad](https://user-images.githubusercontent.com/41333766/43456682-56132608-94bc-11e8-8db5-d9c1dad6ec6a.png)

**Comment by Brownie956** [comment]
Buttons run off the bottom in landscape mode.

![home-page-buttons](https://user-images.githubusercontent.com/11007335/44022530-c1dd6100-9edf-11e8-929c-65763b684bcd.PNG)
