### ISSUE TITLE
BUG: When in iPad landscape mode, the disclaimer page’s second paragraph (re: image storage) is cut off by a white background.

### ISSUE THREAD

**Issue by KyleADay** [bin-nuance-bat/project#239]
## DESCRIPTION

**Steps to reproduce:** 
- Start the app and turn to landscape mode
- Navigate to the disclaimer page
- Scroll down

**Expected behaviour:** 
- The second paragraph should be fully legible
- The background should remain blue

**Observed behaviour:** 
- The second paragraph is cut off by a white background

![239 honesty-store-kiosk firebaseapp com_ ipad 1](https://user-images.githubusercontent.com/41333766/43456648-32c788f6-94bc-11e8-9dc4-81b384fe9ad9.png)

**Comment by Brownie956** [comment]
Page runs off the bottom
![disclaimer-page-buttons](https://user-images.githubusercontent.com/11007335/44022790-92ecb854-9ee0-11e8-843d-0a13dce39740.PNG)
