### ISSUE TITLE
As an admin, I want to be authenticate the kiosk instance to interact with firebase, to enable images to be sent

### ISSUE THREAD

**Issue by paulhands** [bin-nuance-bat/project#259]
AC:

- If the kiosk is not logged in as a kiosk user, admin can select a button on the homepage to access log in page, and log in as a kiosk user.
- Once logged in, should stay logged in, as long as possible

**Comment by isaac-lapworth** [comment]
`logged in as a kiosk user` as in an admin user?
Also, are we bothered about waiting for a UX design for the button since it's going on the homepage? Could make the button invisible for the time being

**Comment by paulhands** [comment]
@isaac-lapworth think @HelloUniverseNo31415 is handling this with Chris, might be worth double checking with both of those about how it's going before jumping in.

That said:

we are imagining a user that isn't admin but is log-in-able, meaning they log in to firebase first, then can use the app. That protects the slack token

**Comment by isaac-lapworth** [comment]
Thanks - makes sense.  Gurveer is handling this issue

**Comment by Brownie956** [comment]
• Do we have any UX on what should happen when an unauthorised user logs in?
• We reach the home page and continue to make retry request to the cloud functions. These return 500 errors which we shouldn't really be returning. If it's an unauthenticated error, we should be returning a 401

**Comment by Brownie956** [comment]
Following discussion: 

- We can ignore UX factors when an unauthenticated user logs in as this is out of scope.
- We should return a 403 (forbidden) response code from the cloud functions when an unauthorised user attempts to use them and a 401 (unauthenticated) when invalid or no authentication is provided
