### ISSUE TITLE
BUG: When switching between online and offline on the scan item page, the video feed eventually fails to load when online

### ISSUE THREAD

**Issue by KyleADay** [bin-nuance-bat/project#287]
## DESCRIPTION

**Steps to reproduce:** 
- Navigate to `/scanitem` page
- Switch between online and offline modes a few times

**Expected behaviour:** 
- The video feed should load when connected online

**Observed behaviour:** 
- The video feed fails to load after a few times

**Comment by HelloUniverseNo31415** [comment]
I moved this from in triage because I fixed it based on Kyle's comments on issue 200 which was in todo
