### ISSUE TITLE
BUG - In full screen mode - Timeout notifications doesn't show

### ISSUE THREAD

**Issue by Brownie956** [bin-nuance-bat/project#311]
## DESCRIPTION
When the user is on any page in the system, a timeout notification should be shown after 45 seconds of inactivity so that the system can reset back to the home screen

**Steps to reproduce:** 
- Place the application in full screen mode (no ipad mode, I.E browser mode)
- Navigate to any page in the system that isn't the home page or the success page
- Wait 45 seconds
- BUG - Timeout notification doesn't show

**Expected behaviour:** 
- Timeout notification should show, giving the user 20 seconds to respond with activity in order to dismiss it

**Observed behaviour:** 
- Timeout notification doesn't show after 45 seconds of inactivity

**Comment by paulhands** [comment]
Timeout shouldn't appear on item recognition page, home page, success page, snackchat page (in dev)

**Comment by Brownie956** [comment]
The timeout requires a touch event to initially trigger the timer. The timer should trigger when the page renders
