### ISSUE TITLE
BUG - Lifecycle warning shows when user reaches success page

### ISSUE THREAD

**Issue by Brownie956** [bin-nuance-bat/project#314]
## BUG: A lifecycle warning is shown in the console when the user reaches the success page
`Warning: SuccessPage has a method called componentDidUnmount(). But there is no such lifecycle method. Did you mean componentWillUnmount()?`

## DESCRIPTION
A warning in the console is shown when the user reaches the success page

**Steps to reproduce:** 
- Navigate through the system keeping the dev console open
- BUG - when the user reaches the success page a warning is shown in the console
`Warning: SuccessPage has a method called componentDidUnmount(). But there is no such lifecycle method. Did you mean **componentWillUnmount()?`

**Expected behaviour:** 
- No warning is shown

**Observed behaviour:** 
- A lifecycle warning is shown in the console

**Comment by HelloUniverseNo31415** [comment]
I'm moving this directly to done as it has been merged in. The fix was already in a separate PR when the issue was raised.
