### ISSUE TITLE
BUG - User has the ability to spam someone with slack messages

### ISSUE THREAD

**Issue by Brownie956** [bin-nuance-bat/project#325]
## DESCRIPTION
On the slack handle page (`/slackname`), when the user selects a user they must click the confirmation button to send the slack message. This doesn't prevent the user from clicking the button multiple times, meaning the user can span the selected user.

**Steps to reproduce:** 
- Navigate through either the snack chat or default path to the `/slackname` page
- Select a slack account
- Click the 'next' button multiple times
- BUG - Multiple messages are sent to the selected user

**Expected behaviour:** 
- The user should only be able to send one single slack message. This could be by implementing a restriction on client side (UI restriction), server side (cloud function api restriction) or both.

**Observed behaviour:** 
- The user can send multiple slack messages to the selected slack account

**Comment by Brownie956** [comment]
For a more concrete UX, it would be good if we could lock the user out from doing anything on the page. At the moment, you can click 'Next' and then while it's in 'sending' mode, click on a different slack name.

**Comment by Brownie956** [comment]
Left comment in #337

**Comment by isaac-lapworth** [comment]
Have added a change for #337 to this branch (`slack-sending`)

Safe to close this issue ?
