### ISSUE TITLE
As a user I want to see item qualifiers on the edit snack and snack confirmation pages to better understand which product is which

### ISSUE THREAD

**Issue by cainy393** [bin-nuance-bat/project#335]
AC:

- Edit Snack and Snack Confirmation pages match the new UX designs

**Comment by HelloUniverseNo31415** [comment]
https://drive.google.com/drive/folders/1IDnpKBTRryg4jGsyhP3AOCokx28lcrow

**Comment by Brownie956** [comment]
The confirmation page is missing the variety as per the UX designs. See screenshots:

Expected (Walkers doesn't actually have a qualifier but McCoys and Jacobs do):
![confirmation-page-qualifier-ux](https://user-images.githubusercontent.com/11007335/44204887-59254000-a14c-11e8-9545-e809a9972a5e.PNG)

Actual:
![confirmation-page-qualifier](https://user-images.githubusercontent.com/11007335/44204915-75c17800-a14c-11e8-8599-9fa899448052.PNG)
