### ISSUE TITLE
BUG: pressing back on a page using the webcam causes a crash

### ISSUE THREAD

**Issue by isaac-lapworth** [bin-nuance-bat/project#351]
## DESCRIPTION

**Steps to reproduce:** 
- Go to the page where you scan your item or take a snackchat
- Press back
- Wait about a second and the app crashes

**Expected behaviour:** 
- Should go to the previous page

**Observed behaviour:** 
- App crashes (due to methods being called on objects that no longer exist)

**Comment by Brownie956** [comment]
See comment in #263 about buying an 'UNKNOWN'

**Comment by Brownie956** [comment]
This is technically complete
