### ISSUE TITLE
Slack messages for items priced £1 or above

### ISSUE THREAD

**Issue by HelloUniverseNo31415** [bin-nuance-bat/project#357]
When sending a reminder about buying pot noodles, the slack message displays the price as '121p', it should be '£1.21'.

**Comment by isaac-lapworth** [comment]
Change to show £ and p is on branch `issue-357`
Running `firebase deploy --only functions` says it has deployed the new functions but the changes don't appear on the deployment, I'm missing something obvious

**Comment by HelloUniverseNo31415** [comment]
Only main firebase deployment can call servers outside of google
