### ISSUE TITLE
No image sent to database when no guess is strong enough

### ISSUE THREAD

**Issue by HelloUniverseNo31415** [bin-nuance-bat/project#374]
## DESCRIPTION

**Steps to reproduce:** 
- Go through the using an image that means the app cannot guess

**Expected behaviour:** 
- At the end of the flow, the admin panel should receive an image from that flow

**Observed behaviour:** 
- No image received

**Comment by Brownie956** [comment]
When the application doesn't recognise an item and you click back on the edit snack page, an error is thrown
