### ISSUE TITLE
Flow fails if you go through too fast

### ISSUE THREAD

**Issue by HelloUniverseNo31415** [bin-nuance-bat/project#378]
## DESCRIPTION

**Steps to reproduce:** 
- Go through the app (fresh instance) and get to the slack page very quickly (before slack users are fetched)

**Expected behaviour:** 
-App should wait until slack users are fetched and then display them

**Observed behaviour:** 
- App fails

**Comment by tclarke-scottlogic** [comment]
Appears fixed, tested and found it does re-render when the response is processed.
