### ISSUE TITLE
User re prompted for camera permission on  after timeout

### ISSUE THREAD

**Issue by HelloUniverseNo31415** [bin-nuance-bat/project#393]
## DESCRIPTION
Only happens on ipad not in PC browser 

**Steps to reproduce:** 
- Cause a timeout to occur
 - Navigate to the camera page

**Expected behaviour:** 
- Video feed should display

**Observed behaviour:** 
- User prompted for camera permission

**Comment by Brownie956** [comment]
This doesn't work in Firefox for some reason. However it works in Chrome and Safari so we can put this to one side as a known issue.
