### ISSUE TITLE
BUG - On admin/collection page, select box doesn't render in chrome

### ISSUE THREAD

**Issue by Brownie956** [bin-nuance-bat/project#405]
## DESCRIPTION
On the admin/collection page, the item select box doesn't fully render and only shows the selected text.

**Steps to reproduce:** 
- In chrome, navigate to the /admin/collection page
- BUG - item select box doesn't render

**Expected behaviour:** 
- Item select box on collection page renders in all browsers (including Chrome)

**Observed behaviour:** 
- In Chrome, the item select box on the collection page doesn't render

**Comment by tclarke-scottlogic** [comment]
Could Not Replicate
