### ISSUE TITLE
As a user I want to understand how my privacy is being protected, so the app can use my images to improve the ML model

### ISSUE THREAD

**Issue by paulhands** [bin-nuance-bat/project#90]
AC:

- Research securing the database in firebase so only admin users can access them - should have an outcome of the expectation of how it will work (can be high level)

**Comment by isaac-lapworth** [comment]
From a quick look through the docs, it looks like read/write access to the firestore can be restricted by adding some authentication method to the app, then using the users' emails/auth IDs in the rules configuration page.

For example, we could create a 'public' account without r/w access that is permanently signed in for use at the kiosk, and then an admin account Chris can use to log in and read the training/item data etc.
